export { DefaultElement } from './components/DefaultElement/DefaultElement.component';
export { Leaf } from './components/Leaf/Leaf.component';
export { LinkElement } from './components/LinkElement/LinkElement.component';
export { Placeholder } from './components/Placeholder/Placeholder.component';
export { Preview } from './components/Preview/Preview.component';
export { PrismVariableLeaf } from './components/PrismVariableLeaf/PrismVariableLeaf.component';
export * from './components/Toolbar';
export { SlateEditorTwoLineInput } from './components/TwoLineInput/TwoLineInput.component';
export { VariableElement } from './components/VariableElement/VariableElement.component';
export { usePluginOptions } from './contexts/PluginsOptions.context';
export { createEditor } from './editor/editor';
export type { VariableItem } from './editor/plugins/variables.plugin';
export * from './editor/staticEditor';
export { useEditorHotkey as useHotkey } from './hooks/hotkeys.hook';
export { useEditorForceNormalize as useForceNormalize } from './hooks/normalize.hook';
export { useSetupEditor as useSetup } from './hooks/setup.hook';
export { SlateEditor as Component } from './SlateEditor.component';
export { ElementProperty, ElementType, PluginType, TextProperty, VariableElementVariant } from './SlateEditor.constant';
export * as css from './SlateEditor.css';
export type { LinkElement as LinkElementType, VariableElement as VariableElementType } from './SlateEditor.interface';
export * from './SlateEditor.interface';
